server.port: ${PORT:8080}
spring:
  application.name: zuul
  cloud:
    loadbalancer:
      retry:
        enabled: true

zuul:
  ignoredServices: "*"
  routes:
    spring-cloud-eureka-client:
      path: "/client/**"
      retryable: true

endpoints:
  restart.enabled: true
  shutdown.enabled: true
  health.sensitive: false

management:
  server:
    port: 8081
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


ribbon:
  # 재시도여부 / 재시도횟수 / 다른서버로재시도횟수
  retryable: true
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 5
  # 현 클라이언트의 모든 재시도 여부
  OkToRetryOnAllOperations: true
  # 제한시간 : 연결 / 소켓 / 리드
  ConnectTimeout: 500
  SocketTimeut: 500
  ReadTimeout: 5000