server.port: ${PORT:8080}
spring.application.name: zuul

zuul:
  ignoredServices: "*"
  routes:
    SPRING-CLOUD-EUREKA-CLIENT: "/client/**"

endpoints:
  restart.enabled: true
  shutdown.enabled: true
  health.sensitive: false

management:
  server:
    port: 8081
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

ribbon:
  retryable: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: true
  ConnectTimeout: 30000
  ReadTimeout: 30000